// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    NumberPad: typeof import('./src/components/Money/NumberPad.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tags: typeof import('./src/components/Money/Tags.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    Type: typeof import('./src/components/Money/Type.vue')['default']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanPopup: typeof import('vant/es')['Popup']
  }
}

export {}
